import { User } from '../types/user';
import { Project } from '../types/project';
import { WeeklyReport } from '../types/report';
import { ReportReview, ReportVersion } from '../types/review';

export const DUMMY_USERS: User[] = [
  {
    id: 1,
    name: 'Alex Morgan',
    email: 'alex.morgan@teampulse.io',
    role: 'TEAM_MEMBER',
    department: 'Frontend Engineering',
    joinedDate: '2024-03-15',
    reportCompletionRate: 95,
  },
  {
    id: 2,
    name: 'Sarah Chen',
    email: 'sarah.chen@teampulse.io',
    role: 'MANAGER',
    department: 'Engineering Leadership',
    joinedDate: '2023-01-10',
    reportCompletionRate: 100,
  },
  {
    id: 3,
    name: 'David Miller',
    email: 'david.miller@teampulse.io',
    role: 'ADMIN',
    department: 'Operations',
    joinedDate: '2022-11-01',
    reportCompletionRate: 98,
  },
  {
    id: 4,
    name: 'Elena Rostova',
    email: 'elena.r@teampulse.io',
    role: 'TEAM_MEMBER',
    department: 'Backend Infrastructure',
    joinedDate: '2024-06-01',
    reportCompletionRate: 88,
  },
  {
    id: 5,
    name: 'Marcus Vance',
    email: 'marcus.vance@teampulse.io',
    role: 'TEAM_MEMBER',
    department: 'UI/UX Design',
    joinedDate: '2024-02-20',
    reportCompletionRate: 92,
  },
  {
    id: 6,
    name: 'Priya Sharma',
    email: 'priya.sharma@teampulse.io',
    role: 'TEAM_MEMBER',
    department: 'Mobile Engineering',
    joinedDate: '2024-07-12',
    reportCompletionRate: 90,
  },
  {
    id: 7,
    name: 'James O\'Connor',
    email: 'james.o@teampulse.io',
    role: 'TEAM_MEMBER',
    department: 'QA & Testing',
    joinedDate: '2024-04-05',
    reportCompletionRate: 85,
  },
  {
    id: 8,
    name: 'Sophia Patel',
    email: 'sophia.patel@teampulse.io',
    role: 'MANAGER',
    department: 'Product Management',
    joinedDate: '2023-08-18',
    reportCompletionRate: 100,
  },
];

export const DUMMY_PROJECTS: Project[] = [
  {
    id: 101,
    name: 'TeamPulse Platform 2.0',
    description: 'Next-generation weekly reporting and team sync suite.',
    active: true,
    memberCount: 5,
    reportCount: 14,
  },
  {
    id: 102,
    name: 'Core API Gateway',
    description: 'High-throughput microservices gateway and authentication provider.',
    active: true,
    memberCount: 3,
    reportCount: 10,
  },
  {
    id: 103,
    name: 'Mobile App Redesign',
    description: 'Cross-platform iOS & Android workflow companion app.',
    active: true,
    memberCount: 4,
    reportCount: 8,
  },
  {
    id: 104,
    name: 'Analytics Engine & Pipeline',
    description: 'Real-time telemetry and aggregate reporting metrics engine.',
    active: true,
    memberCount: 2,
    reportCount: 6,
  },
  {
    id: 105,
    name: 'Legacy Migration (V1 to Cloud)',
    description: 'Deprecation and data migration of v1 legacy database.',
    active: false,
    memberCount: 1,
    reportCount: 12,
  },
];

export const DUMMY_REPORTS: WeeklyReport[] = [
  {
    id: 1,
    userId: 1,
    userName: 'Alex Morgan',
    projectId: 101,
    projectName: 'TeamPulse Platform 2.0',
    weekStartDate: '2026-09-01',
    weekEndDate: '2026-09-07',
    status: 'SUBMITTED',
    nextWeekTasks: '- Finalize Version History diff visualizer modal\n- Optimize bundle size and dynamic routing chunks\n- Conduct cross-browser testing on Safari & Firefox Mobile',
    notes: 'Overall smooth velocity this sprint. Waiting on final UX signoff for project filters.',
    submittedAt: '2026-09-06T16:30:00Z',
    approvedAt: null,
    tasks: [
      {
        id: 1001,
        taskName: 'Implement Responsive Navigation Header & Mobile Drawer',
        priority: 'HIGH',
        plannedPercentage: 100,
        actualPercentage: 100,
        status: 'COMPLETED',
        plannedHours: 12,
        actualHours: 11,
        deliverable: 'https://github.com/teampulse/frontend/pull/42',
      },
      {
        id: 1002,
        taskName: 'Build Report Form with Dynamic Task & Time Distribution Sections',
        priority: 'CRITICAL',
        plannedPercentage: 100,
        actualPercentage: 100,
        status: 'COMPLETED',
        plannedHours: 16,
        actualHours: 18,
        deliverable: 'https://github.com/teampulse/frontend/pull/45',
      },
      {
        id: 1003,
        taskName: 'Refactor State Management & Mock Data Hooks',
        priority: 'MEDIUM',
        plannedPercentage: 100,
        actualPercentage: 85,
        status: 'IN_PROGRESS',
        plannedHours: 8,
        actualHours: 7,
        deliverable: 'WIP PR #48',
      },
    ],
    blockers: [
      {
        id: 2001,
        description: 'Waiting on backend response schema for bulk report export API',
        keyIssue: true,
        resolved: false,
      },
    ],
    achievements: [
      {
        id: 3001,
        description: 'Reduced initial render load time by 40% with memoized component state',
        keyAchievement: true,
      },
      {
        id: 3002,
        description: 'Achieved 100% test coverage on reusable UI common components',
        keyAchievement: false,
      },
    ],
    timeEntries: [
      { id: 4001, taskType: 'DEVELOPMENT', hours: 24 },
      { id: 4002, taskType: 'MEETINGS', hours: 6 },
      { id: 4003, taskType: 'TESTING', hours: 4 },
      { id: 4004, taskType: 'DOCUMENTATION', hours: 2 },
    ],
  },
  {
    id: 2,
    userId: 4,
    userName: 'Elena Rostova',
    projectId: 102,
    projectName: 'Core API Gateway',
    weekStartDate: '2026-09-01',
    weekEndDate: '2026-09-07',
    status: 'NEEDS_CORRECTION',
    nextWeekTasks: '- Fix rate limiting algorithm for OAuth token endpoint\n- Add database connection pool metrics',
    notes: 'Please review comments regarding missing unit test breakdown.',
    submittedAt: '2026-09-05T14:15:00Z',
    approvedAt: null,
    tasks: [
      {
        id: 1004,
        taskName: 'Migrate Auth Middleware to JWT RSA256 Validation',
        priority: 'CRITICAL',
        plannedPercentage: 100,
        actualPercentage: 100,
        status: 'COMPLETED',
        plannedHours: 16,
        actualHours: 15,
        deliverable: 'PR #108 - Core API',
      },
      {
        id: 1005,
        taskName: 'Setup Redis Caching for Weekly Status Aggregates',
        priority: 'HIGH',
        plannedPercentage: 100,
        actualPercentage: 60,
        status: 'IN_PROGRESS',
        plannedHours: 14,
        actualHours: 12,
        deliverable: 'Feature branch bg/redis-cache',
      },
    ],
    blockers: [
      {
        id: 2002,
        description: 'Staging Redis cluster hit memory limit during load simulation',
        keyIssue: true,
        resolved: true,
      },
      {
        id: 2003,
        description: 'Intermittent timeout on third-party webhook notification test server',
        keyIssue: false,
        resolved: false,
      },
    ],
    achievements: [
      {
        id: 3003,
        description: 'Successfully load tested OAuth endpoint at 10,000 req/sec',
        keyAchievement: true,
      },
    ],
    timeEntries: [
      { id: 4005, taskType: 'DEVELOPMENT', hours: 22 },
      { id: 4006, taskType: 'RESEARCH', hours: 8 },
      { id: 4007, taskType: 'MEETINGS', hours: 4 },
      { id: 4008, taskType: 'TESTING', hours: 3 },
    ],
  },
  {
    id: 3,
    userId: 5,
    userName: 'Marcus Vance',
    projectId: 101,
    projectName: 'TeamPulse Platform 2.0',
    weekStartDate: '2026-09-01',
    weekEndDate: '2026-09-07',
    status: 'APPROVED',
    nextWeekTasks: '- Deliver high-fidelity Figma spec for Manager Review workflow\n- Mobile responsive design audit for tablets',
    notes: 'Design tokens fully aligned with brand guidelines.',
    submittedAt: '2026-09-04T11:00:00Z',
    approvedAt: '2026-09-05T09:20:00Z',
    tasks: [
      {
        id: 1006,
        taskName: 'Design System Token Update & Color Palette Harmonization',
        priority: 'HIGH',
        plannedPercentage: 100,
        actualPercentage: 100,
        status: 'COMPLETED',
        plannedHours: 20,
        actualHours: 20,
        deliverable: 'Figma File: TeamPulse V2 Design Specs',
      },
      {
        id: 1007,
        taskName: 'User Testing Session for Executive Management Dashboard',
        priority: 'MEDIUM',
        plannedPercentage: 100,
        actualPercentage: 100,
        status: 'COMPLETED',
        plannedHours: 10,
        actualHours: 10,
        deliverable: 'User Feedback Report Document',
      },
    ],
    blockers: [],
    achievements: [
      {
        id: 3004,
        description: 'Finalized complete accessibility palette compliant with WCAG 2.1 AA',
        keyAchievement: true,
      },
    ],
    timeEntries: [
      { id: 4009, taskType: 'RESEARCH', hours: 14 },
      { id: 4010, taskType: 'DEVELOPMENT', hours: 12 },
      { id: 4011, taskType: 'MEETINGS', hours: 6 },
    ],
  },
  {
    id: 4,
    userId: 6,
    userName: 'Priya Sharma',
    projectId: 103,
    projectName: 'Mobile App Redesign',
    weekStartDate: '2026-09-01',
    weekEndDate: '2026-09-07',
    status: 'DRAFT',
    nextWeekTasks: '- Complete offline sync SQLite cache store\n- Push v1.2 beta to TestFlight',
    notes: 'Drafting tasks, will submit before end of day Monday.',
    submittedAt: null,
    approvedAt: null,
    tasks: [
      {
        id: 1008,
        taskName: 'React Native Navigation setup with Deep Linking',
        priority: 'HIGH',
        plannedPercentage: 100,
        actualPercentage: 90,
        status: 'IN_PROGRESS',
        plannedHours: 18,
        actualHours: 16,
        deliverable: 'PR #12 - Mobile Repo',
      },
      {
        id: 1009,
        taskName: 'Biometric Login Integration (FaceID / TouchID)',
        priority: 'MEDIUM',
        plannedPercentage: 100,
        actualPercentage: 100,
        status: 'COMPLETED',
        plannedHours: 12,
        actualHours: 11,
        deliverable: 'PR #14 - Mobile Repo',
      },
    ],
    blockers: [
      {
        id: 2004,
        description: 'Apple Developer portal signing certificate expiration renewal pending',
        keyIssue: true,
        resolved: false,
      },
    ],
    achievements: [],
    timeEntries: [
      { id: 4012, taskType: 'DEVELOPMENT', hours: 20 },
      { id: 4013, taskType: 'TESTING', hours: 6 },
      { id: 4014, taskType: 'MEETINGS', hours: 3 },
    ],
  },
  {
    id: 5,
    userId: 7,
    userName: 'James O\'Connor',
    projectId: 104,
    projectName: 'Analytics Engine & Pipeline',
    weekStartDate: '2026-09-01',
    weekEndDate: '2026-09-07',
    status: 'APPROVED',
    nextWeekTasks: '- Write end-to-end automated Playwright test suite for report creation\n- Integrate CI test reporting to Slack channel',
    notes: 'All core regression suites passing cleanly.',
    submittedAt: '2026-09-04T18:00:00Z',
    approvedAt: '2026-09-05T10:15:00Z',
    tasks: [
      {
        id: 1010,
        taskName: 'Automated E2E Test Suite for Manager Review Flow',
        priority: 'HIGH',
        plannedPercentage: 100,
        actualPercentage: 100,
        status: 'COMPLETED',
        plannedHours: 16,
        actualHours: 15,
        deliverable: 'Playwright Specs in e2e/',
      },
      {
        id: 1011,
        taskName: 'Performance Benchmarking on Dashboard Data Loads',
        priority: 'MEDIUM',
        plannedPercentage: 100,
        actualPercentage: 100,
        status: 'COMPLETED',
        plannedHours: 12,
        actualHours: 12,
        deliverable: 'K6 Benchmark Summary',
      },
    ],
    blockers: [],
    achievements: [
      {
        id: 3005,
        description: 'Uncovered and logged 4 critical edge-case bugs prior to production release',
        keyAchievement: true,
      },
    ],
    timeEntries: [
      { id: 4015, taskType: 'TESTING', hours: 22 },
      { id: 4016, taskType: 'DOCUMENTATION', hours: 6 },
      { id: 4017, taskType: 'MEETINGS', hours: 4 },
    ],
  },
  {
    id: 6,
    userId: 1,
    userName: 'Alex Morgan',
    projectId: 101,
    projectName: 'TeamPulse Platform 2.0',
    weekStartDate: '2026-08-25',
    weekEndDate: '2026-08-31',
    status: 'APPROVED',
    nextWeekTasks: '- Prepare UI components for team management dashboard\n- Finalize Tailwind design tokens',
    notes: 'Previous week report.',
    submittedAt: '2026-08-30T17:00:00Z',
    approvedAt: '2026-08-31T09:00:00Z',
    tasks: [
      {
        id: 1012,
        taskName: 'Setup React Router V7 & Role-Based Navigation System',
        priority: 'CRITICAL',
        plannedPercentage: 100,
        actualPercentage: 100,
        status: 'COMPLETED',
        plannedHours: 20,
        actualHours: 19,
        deliverable: 'PR #30',
      },
    ],
    blockers: [],
    achievements: [
      {
        id: 3006,
        description: 'Successfully established routing foundation for multi-role user areas',
        keyAchievement: true,
      },
    ],
    timeEntries: [
      { id: 4018, taskType: 'DEVELOPMENT', hours: 28 },
      { id: 4019, taskType: 'MEETINGS', hours: 4 },
    ],
  },
];

export const DUMMY_REVIEWS: Record<number, ReportReview[]> = {
  2: [
    {
      id: 5001,
      managerId: 2,
      managerName: 'Sarah Chen',
      versionNumber: 1,
      action: 'REQUESTED_CHANGES',
      comment: 'Great progress on the JWT migration, Elena! However, please break down actual hours spent on Redis caching and specify the expected resolution date for the Redis cluster memory issue in your blockers section.',
      createdAt: '2026-09-05T16:00:00Z',
    },
  ],
  3: [
    {
      id: 5002,
      managerId: 2,
      managerName: 'Sarah Chen',
      versionNumber: 1,
      action: 'APPROVED',
      comment: 'Excellent work on the design system harmonizing! The contrast levels look fantastic and WCAG compliance is spot on.',
      createdAt: '2026-09-05T09:20:00Z',
    },
  ],
  5: [
    {
      id: 5003,
      managerId: 8,
      managerName: 'Sophia Patel',
      versionNumber: 1,
      action: 'APPROVED',
      comment: 'Great job identifying the edge-case bugs early in test simulation. Approved!',
      createdAt: '2026-09-05T10:15:00Z',
    },
  ],
};

export const DUMMY_VERSIONS: Record<number, ReportVersion[]> = {
  1: [
    {
      id: 6001,
      versionNumber: 1,
      createdAt: '2026-09-06T16:30:00Z',
      submittedBy: 'Alex Morgan',
      contentSnapshot: JSON.stringify(DUMMY_REPORTS[0]),
    },
  ],
  2: [
    {
      id: 6002,
      versionNumber: 1,
      createdAt: '2026-09-05T14:15:00Z',
      submittedBy: 'Elena Rostova',
      contentSnapshot: JSON.stringify(DUMMY_REPORTS[1]),
      reviewComment: 'Changes requested by Sarah Chen: Add details for Redis memory limit and hours breakdown.',
    },
    {
      id: 6003,
      versionNumber: 2,
      createdAt: '2026-09-06T10:00:00Z',
      submittedBy: 'Elena Rostova',
      contentSnapshot: JSON.stringify({
        ...DUMMY_REPORTS[1],
        notes: 'Updated hours breakdown and blocker notes per manager feedback.',
      }),
    },
  ],
  3: [
    {
      id: 6004,
      versionNumber: 1,
      createdAt: '2026-09-04T11:00:00Z',
      submittedBy: 'Marcus Vance',
      contentSnapshot: JSON.stringify(DUMMY_REPORTS[2]),
    },
  ],
};
